# Generated by Backstage Software Template
# Bucket: ${{ values.environment }}-${{ values.bucket_name }}
# Owner:  ${{ values.owner }}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Remote state — store in your existing state bucket
  backend "s3" {
    bucket = "<YOUR_TF_STATE_BUCKET>"
    key    = "${{ values.environment }}/${{ values.bucket_name }}/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region = "us-east-1"
}

data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "this" {
  bucket        = "${{ values.environment }}-${{ values.bucket_name }}-${data.aws_caller_identity.current.account_id}"
  force_destroy = true

  tags = {
    Name        = "${{ values.bucket_name }}"
    Environment = "${{ values.environment }}"
    Owner       = "${{ values.owner }}"
    ManagedBy   = "backstage-scaffolder"
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket                  = aws_s3_bucket.this.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  bucket = aws_s3_bucket.this.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

{% if values.versioning %}
resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id
  versioning_configuration {
    status = "Enabled"
  }
}
{% endif %}

{% if values.lifecycle_days > 0 %}
resource "aws_s3_bucket_lifecycle_configuration" "this" {
  bucket = aws_s3_bucket.this.id
  rule {
    id     = "expire-objects"
    status = "Enabled"
    expiration {
      days = ${{ values.lifecycle_days }}
    }
  }
}
{% endif %}

output "bucket_name" {
  value = aws_s3_bucket.this.id
}

output "bucket_arn" {
  value = aws_s3_bucket.this.arn
}
